### ISSUE TITLE
Turn off browser caching for local DEV work?

### ISSUE THREAD

**Issue by mosaiceye** [docker-library/wordpress#114]
When using this docker file for local development, my local PHP file updates don't happen right away. How can I disable browser caching? For local dev, work? I'm currently using Kitematic (Beta) 0.9.4, with my WP code pointing to a local folder on my host MAC from within my User/Sites folder. Any ideas on how to change this?

**Comment by tianon** [comment]
This is heavily related to the discussion following https://github.com/docker-library/wordpress/pull/103#issuecomment-159406808.

I think it might actually make sense to remove the explicit setting of `opcache.revalidate_freq` from our default configuration, since the default value of `2` (https://secure.php.net/manual/en/opcache.configuration.php) for how often `opcache` will do a `stat` to determine freshness really ought to be a fairly reasonable compromise (especially since `stat` is a reasonably lightweight op, especially compared to recompiling the file).

**Comment by tianon** [comment]
(ie, it's not actually browser caching that's biting you, but the PHP opcache)

**Comment by tianon** [comment]
@yosifkit what do you think about either setting a more conservative value for our provided `opcache.revalidate_freq` or just using the more conservative default value?

**Comment by yosifkit** [comment]
Setting ours to be explicitly `2` gives us the same as the default, but also makes it obvious where the value comes from.
