### ISSUE TITLE
Backup of wordpress container.

### ISSUE THREAD

**Issue by ankurgla22** [docker-library/wordpress#136]
Is there any way to get automatic backup of  wordpress container.
Like setting environmental variable.

For Example in case of redmine container -
--env='REDMINE_BACKUP_SCHEDULE=daily' --env='REDMINE_BACKUP_TIME=04:00' --env='REDMINE_BACKUP_EXPIRY=7257600'

**Comment by yosifkit** [comment]
No, this would have to be something you set in a repeating task (like jenkins or cron) outside of the Wordpress container; most likely it would be a new container with --`volumes-from` your Wordpress container so that it can copy them, and then access to some other location to store and manage your backups.
