### ISSUE TITLE
Wordpress scheduler issue

### ISSUE THREAD

**Issue by EvertMDC** [docker-library/wordpress#157]
Hello guys,

Thank you for creating this container, it is much appreciated.

There seems to be a bug in at least the latest image where for example scheduled posts don't get posted. The issue is bigger than that as nothing that relies on the wp-cron like the backupwordpress plugins works. No issues on here seem to address this.

I'd be happy to give a hand in sorting this out but so far I've been unsuccessful.
Would it be possible to confirm this behaviour and point me in the good direction please?

Many thanks,
Evert

**Comment by Julianoe** [comment]
This issue is old and opened since a long time. Did you manage to sort things out?
From what i tested the cron tasks of schedule publishing posts for example seem to work.
Backup wordpress extensions seem to have problems because of the zip or mysqldump failing.

**Comment by tianon** [comment]
In a stock WordPress install, Cron runs automatically by visitors visiting the site.  No visitors, no cron.

(Since this container isn't running any sort of `crond` to run them automatically, and WordPress upstream supports and even encourages installation in shared hosting environments where adjusting host Cron settings isn't always reasonable or possible.)

There are a number of articles on the internet (such as https://tommcfarlin.com/wordpress-cron-jobs/) about setting up WordPress cron in other ways -- you'll likely need to use `docker exec` or `wget` as described in the linked post to make them work appropriately inside your WordPress-in-a-container environment if you don't have enough traffic to support the built-in cron functionality (or it is insufficient for other reasons).

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
