### ISSUE TITLE
Apache config

### ISSUE THREAD

**Issue by NathanKleekamp** [docker-library/wordpress#159]
Thanks for the hard work being put into this image. 

I'm a new Docker user, and I'm struggling to understand how I can update the Apache config with this image. I've been able to successfully get a Wordpress up and running, but now I'm struggling to get past the defaults to make it really usable for me.

I have looked at the PHP image docs, but there's really no mention in there. What am I missing? Thanks for looking and for any advice about how to proceed.

**Comment by pasali** [comment]
you can mount any file or dir to docker image. For example for virutalhost config you can do something like this:

     volumes:
      - ./apache-vhost.conf:/etc/apache2/sites-enabled/000-default.conf

**Comment by mnewmedia** [comment]
this works:
```
 volumes:
      - ./data/html:/var/www/html
      - ./data/log/apache2:/var/log/apache2
      - ./data/sites-enabled:/etc/apache2/sites-enabled/
```
But this not:
```
 volumes:
      - ./data/html:/var/www/html
      - ./data/log/apache2:/var/log/apache2
      - ./data/etc/apache2:/etc/apache2
```
Then i get: `apache2: Could not open configuration file /etc/apache2/apache2.conf: No such file or directory`
Somebody knows why?

**Comment by yosifkit** [comment]
@mnewmedia, files that exist in the image are masked when you mount a local directory into the container, so you hid the default config file when you did `- ./data/etc/apache2:/etc/apache2`.  If you want to mount the whole `/etc/apache2` directory, you will need to provide everything that it provides.

**Comment by mnewmedia** [comment]
@yosifkit  ah thanks for the explaination.

**Comment by tianon** [comment]
Closing since this isn't really an issue but more a request for help.

This image contains a pretty stock install of Debian's Apache packages with PHP built from source, so updating the Apache configuration should be done in the normal Debian ways.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
