### ISSUE TITLE
using localhost or a permanent address

### ISSUE THREAD

**Issue by MichaelLSmith** [docker-library/wordpress#166]
Whenever I start my containers up, I see this message:

 AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message

How and where do I set the ServerName directive so that it's a permanent address? Can I set it so that it's localhost?

**Comment by yosifkit** [comment]
The message is just a warning and shouldn't have any effect on serving WordPress.

**Comment by MichaelLSmith** [comment]
My problem is that it changes almost every time I start up docker. I was hoping to set it to be the same address every time.

**Comment by yosifkit** [comment]
Yes, Docker will assign the next IP address available in the block that it uses. WordPress redirects to whatever URL you first used to access it.  You can [change the site url](https://codex.wordpress.org/Changing_The_Site_URL).

I find the simplest solution for local development on WordPress is to set a `-p 80:80` on the docker run and add a hostname alias for localhost, like `example.com`, to `/etc/hosts` on the docker host and then I can access in the browser under that alias of `example.com`.

It is also possible to assign a static IP to a container: http://stackoverflow.com/a/35359185

**Comment by SamMorrowDrums** [comment]
The idea with Docker is that you can deploy lots of versions of the same thing, so setting the site url to localhost (or custom host as @yosifkit suggests) is what you would do.

Also, it seems unusual that you would use the docker adaptor URL. Why don't you expose 0.0.0.0:<port>:80 when you start the container (replace <port> with a port like 3000)

Then it should always be available as `localhost:<port>` ex. `localhost:3000`.

**Comment by tianon** [comment]
I'm going to close this, since this is Docker and WordPress both working exactly the way they're designed to (and I think there's some good discussion here about the issue -- feel free to continue the discussion if you feel it isn't clear).

I will note that the way I usually solve this for my own deployments of WordPress is by using NGINX in front of the WordPress container to normalize the external endpoint (especially since I usually host several other things on the same server).
