### ISSUE TITLE
Syntax Error in entrypoint.sh - 4.6-apache

### ISSUE THREAD

**Issue by karnajani** [docker-library/wordpress#173]
I don't know much about bash scripts, but I was implementing the fix in #130 from @bkcummins. While tinkering, I tried running the current entrypoint  bash script in an already running container and got the following output:

` root@4c8ad4a5064a:/var/www/html# sh /entrypoint.sh`
` /entrypoint.sh: 97: /entrypoint.sh: Syntax error: "(" unexpected (expecting "fi" )`

I don't know if this syntax error is an issue but I thought I'd bring it up.

**Comment by tianon** [comment]
You're running `/entrypoint.sh` with `sh`, but it's actually a `bash` script (see the `#!/bin/bash` shebang at the top of the script).  Any particular reason you're using `sh /entrypoint.sh` instead of just using `/entrypoint.sh` and letting the kernel/shell determine the appropriate interpreter to use based on the shebang?

**Comment by karnajani** [comment]
@tianon it's because I don't know enough about bash scripts to know that I wasn't supposed to use `sh`

Feel free to close this issue :)

**Comment by tianon** [comment]
Glad we got it figured! :+1:
