### ISSUE TITLE
Emptiness test with docker-entrypoint.sh using GlusterFS volumes

### ISSUE THREAD

**Issue by TerraTech** [docker-library/wordpress#187]
@tianon In reference to:
https://github.com/docker-library/wordpress/blob/8ab70dd61a996d58c0addf4867a768efe649bf65/php7.0/fpm/docker-entrypoint.sh#L46

An 'empty' GlusterFS volume will usually have the following default directory:  **.trashcan**
```
2016-11-28T06:27:44-05:00 WordPress not found in /var/www/html - copying now...
2016-11-28T06:27:44-05:00 WARNING: /var/www/html is not empty - press Ctrl+C now if this is an error!
2016-11-28T06:27:44-05:00 + ls -A
2016-11-28T06:27:44-05:00 .trashcan
2016-11-28T06:27:44-05:00 + sleep 10
2016-11-28T06:28:12-05:00 Complete! WordPress has been successfully copied to /var/www/html
```
How would you feel about the following tweak being submitted as a PR that updates all docker-entrypoint.sh files:
```shell
		if [ "$(ls -A)" != '.trashcan' ]; then
```
This way if the 'ls -A' returns just one result and tests inequality against '.trashcan', it can skip the 10 second penalty for truly empty GlusterFS volumes.

**Comment by tianon** [comment]
:disappointed:

There's a similar problem with some drivers adding a direct `ext4` root filesystem as a volume.

The _best_ solution I can recommend is to give WordPress a subdirectory of the GlusterFS volume rather than the root of the volume, which should be a general solution that'll work cleanly regardless of the image/software in the container which is supposed to consume/use the volume.

Another image-specific alternative would be to add an environment variable to ignore the warning/`sleep`, but IMO that's a bit hackier.

I'm not really comfortable adding an explicit pass for `.trashcan` since that seems like something very specific to GlusterFS -- I haven't seen that anywhere else. :confused:

**Comment by TerraTech** [comment]
@tianon Right, but when is an 'emptiness' really a valid emptiness test?  This image is going to be consumed by Kubernetes deployments and GlusterFS is a baked in as an official volume that many will use.

What if there was an environment variable that could be passed which would allow for a specific directory to be ignored and allow the emptiness test to work correctly?
e.g.
```sh
if [ "$(ls -A)" != "${EMPTY_EXCLUDE}" ]; then
```
It would be scoped for just one directory, and shouldn't be terribly hacky, and would cover both '.trashcan' and 'lost+found' directories or any other one-offs.  It would also provide a focused solution for those that really need it and not harm otherwise.

**Comment by khassel** [comment]
may it is possible to get an environment variable ${SLEEP_TIME_NOT_EMPTY} which is default 10 sec  but we can override it with other values included 0?

**Comment by tianon** [comment]
Fixed via https://github.com/docker-library/wordpress/pull/350 :sweat_smile: :+1:
