### ISSUE TITLE
Container won't run due to errors in entrypoint

### ISSUE THREAD

**Issue by markg85** [docker-library/wordpress#202]
Hi,

The title is just what i "found"... I don't know if i'm doing something wrong or if there really are errors.

My initial run line:
> docker run --name some-wordpress --link mariadb:mysql -p 8090:80 -d wordpress:php7.1-fpm-alpine

Yes, the mariadb container runs just fine. I have an external phpymadmin setup and can access the databases on that container just fine as well.

However, the run line from above immediately exits..

If i go in the container (bash) with a line like this:
> docker run -it 1ab8eae58a34 /bin/bash

(your id will be different)
and then execute as follows:
> /usr/local/bin/docker-entrypoint.sh

it gives me:
> /usr/local/bin/docker-entrypoint.sh: line 26: $1: unbound variable

It's probably very easy to fix this, but how? :)
Am i doing something wrong?

Regards,
Mark

Edit.

I got a few steps further.
If i try to run the container with the steps above (so attaching the *SQL container to it) then it just doesn't work.

If i specify all the options in the run line (host, user, pass, .. database settings) then the container does start and - weirdly enough - port 9000... The examples clearly show port 80 (internally in the container), not 9000. What is that? Why is that?

Anyhow, ignoring the weird port difference, mapping it externally so i can go there. I thought i had it here, that "yay, it works" moment. But after mapping it, i still don't get anything in my browser.

Granted, i'm quite new in docker, but the trouble i have with wordpress is a lot more then just difficulty setting it up. It "smells" like the documentation is incorrect and attaching a *SQL seems to be an issue on it's own.

**Comment by markg85** [comment]
More finding!

Turns out that the wordpress container specifically looks for the environment variables MYSQL_...
The MariaDB container i used happened to use DB_... variables.

Yet the [phpmyadmin](https://github.com/phpmyadmin/docker) container i used to test the database is working just fine. There i also merely attached the mariadb container. I didn't provide any environment variables for that. The phpmyadmin container is apparently doing something different to figure out the database connection. What that might be, i don't know.

So if phpmyadmin can do this, why can't wordpress do the same?
I still don't know why the wordpress container gave me port 9000 instead of 80, that question is still open.

**Comment by tianon** [comment]
For the automatic linking-based configuration to work, your linked container needs to be using the appropriate environment variables.

I would recommend instead that when you run `wordpress`, you should explicitly add `-e WORDPRESS_DB_HOST=... -e WORDPRESS_DB_USER=... -e WORDPRESS_DB_PASSWORD=... -e WORDPRESS_DB_NAME=...` etc. for configuring your `wordpress` instance in a simple, repeatable way.

**Comment by markg85** [comment]
I rather not have information like that visible n the command line. It's quite easy to find those commands later on if you forget to remove them from the bash history.

Also, this is perfect case where the data should be tugged away nicely in the config. In fact, the data is being stored there! It's just the startup script that complains if you don't give those details....

**Comment by yosifkit** [comment]
There is still code that [uses shared environment variables](https://github.com/docker-library/wordpress/blob/d8e5577dcc7096d2b694dda433e2b5c7c4561a82/docker-entrypoint.sh#L29-L35) when available from a `mysql` or `mariadb` container linked to WordPress (`--link mymaria:mysql`).  The variables must be the same as the variables from the [mysql](https://github.com/docker-library/docs/tree/0932b11350a839562630802dbe36996efd84c5ec/mysql#environment-variables) and [maridb](https://github.com/docker-library/docs/tree/0932b11350a839562630802dbe36996efd84c5ec/mariadb#environment-variables) images provided by the official-images project; more specifically `MYSQL_ROOT_PASSWORD` on the database becomes `MYSQL_ENV_MYSQL_ROOT_PASSWORD` when linked to WordPress.

Getting the environment variables from another container through `--link` is [deprecated](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/).  If you are really worried about data leaking into your bash history, we instead recommend using `docker-compose`.  There is even an example on the Docker Hub page and [here](https://github.com/docker-library/docs/tree/0932b11350a839562630802dbe36996efd84c5ec/wordpress#-via-docker-compose) is the source of the Hub page.

You may also want to switch to the `apache` variant of the `wordpress` image, otherwise you will need something in front of WordPress that speaks FastCGI and then serves up http(s), like nginx.  There is an exampleby IndieHosters of [extending the fpm WordPress image](https://github.com/indiehosters/docker-wordpress) and then [using a `docker-compose.yml`](https://github.com/indiehosters/wordpress) to bring it up with `mysql` and `nginx`.

**Comment by markg85** [comment]
Hi,

Oke, that is some interesting information!
I will give that a shot.

Also, thank you very much for telling me about the docker networking stuff.
In my opinion it all becomes much more simpler that way :)

Then you basically have to do:
docker network create fancy_docker_network
docker run --net fancy_docker_network --name database mariadb
docker run --net fancy_docker_network --name mywordpress wordpress

now the wordpress container can connect to database:3306

All you have to ensure is the database name is used for, well, the database and both containers are in the same docker network.

Note: still learning docker as i go.. This network stuff is something i just started playing with about 20 minutes or so.

Anyhow, you answered the questions i had thus closing this issue.
But i do still think that the wordpress container can use a better description at the very least. Having an option where you don't have to set the password in any place other then the wordpress config would also be a big win in my opinion. I really don't get why you would want to have the password in more than 1 place. It only makes it more error prone.

Thank you both for taking the time to respond! 👍
