### ISSUE TITLE
Use DATABASE_URL environment variable if it exists

### ISSUE THREAD

**Issue by alexgleason** [docker-library/wordpress#207]
Some platforms, especially ones based on Heroku (like Dokku) will automatically put a `DATABASE_URL` environment variable into the app container when you link a mysql or mariadb container to it.

Here's an example:

```
DATABASE_URL:           mysql://mariadb:Z1iV5n1Xg7ViiQA1@dokku-mariadb-myappdb:3306/myappdb
```

Where it follows this formatting:

```
protocol://username:password@host:port/database
```

It would make the workflow so much cleaner for Dokku users to utilize this URL when the environment variable exists. At the moment we have to create new `WORDPRESS_*` envvars that match the ones made by Dokku.

**Comment by tianon** [comment]
Sorry for the delay.

I'm not comfortable adding this Heroku-specific functionality into an otherwise generic official image (especially since it would be the first/only official image to do so).

It should be reasonably easy to write a small script which parses that value for the relevant bits and converts them to the environment variables this image expects, or even to write a custom `wp-config.php` which reads that value directly and parses it into the appropriate configuration values directly.  Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with this additional script injected for the startup.
