### ISSUE TITLE
Enable option to install wordpress networks (wordpress multiuser)

### ISSUE THREAD

**Issue by niktrix** [docker-library/wordpress#23]
Enable option to install wordpress networks (wordpress multiuser)

**Comment by mkdizajn** [comment]
Hi guys, 

I may be asking dumb question but also :)

how to properly alter `wp-config` file after **wp** was setup ?

I tried to edit file from inside container with nano editor, but saw there was no vi or nano installed ( which is great )

**Comment by md5** [comment]
@mkdizajn since `/var/www/html` is a volume, you can edit the file from another container that shares its volumes. Looks like [`haron/vim`](https://registry.hub.docker.com/u/haron/vim/) would work:

> docker run -it --rm --volumes-from wordpress -w /var/www/html haron/vim vim wp-config.php

**Comment by md5** [comment]
Actually, that `haron/vim` has issues because it's running as a `dev` user...

O heu! Why aren't there any good vim images? :disappointed: 

Perhaps I'll make one at some point...

**Comment by md5** [comment]
I just realized you can do this:

    docker run -it --rm --volumes-from wordpress -w /var/www/html -u root haron/vim vim wp-config.php

https://github.com/HaronK/docker-vim/issues/1

**Comment by pierreozoux** [comment]
I think to have `multiuser` setup, you can just create your image on top of this one. Can we close this issue now? Thanks

**Comment by lwille** [comment]
As reply to @pierreozoux, mostly because I don't like the attitude: It's still not possible to "just" extend the functionality of `entrypoint.sh` to customize `wp-config.php` at this point, so this ticket was a totally valid request. Of course manual edition using `vim` is not an option for an automated deployment.

A pointer to #8 (and meanwhile #100) would have been useful.
