### ISSUE TITLE
Wordpress behind proxy

### ISSUE THREAD

**Issue by Fail-Unsafe** [docker-library/wordpress#230]
We are behind a proxy, is there any way to install plugins using Wordpress' "Plugins" menu?

It seems the following variables need to be set in wp-config.php:
```
define('WP_PROXY_HOST', 'W.X.Y.Z');
define('WP_PROXY_PORT', '8080');
define('WP_PROXY_USERNAME', '');
define('WP_PROXY_PASSWORD', '');
define('WP_PROXY_BYPASS_HOSTS', 'localhost, ...');
define('WP_USEPROXY', true);
define('WP_TEMP_DIR', ABSPATH . 'wp-content/tmp');
```
as well as the following packages:

- php-curl
- libphp-snoopy
- php5-curl

Is it possible to add these packages and allow the necessary variables to be passed in environment variables?

**Comment by tianon** [comment]
I use WordPress running with this container behind a reverse proxy and don't seem to have any issues installing plugins, so I think for folks to help you you'll need to be more specific about exactly how you're deploying WordPress (as in, the exact `docker run` line used would be helpful) and the exact configuration of your reverse proxy.

Regardless, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!

**Comment by bsauvajon** [comment]
The problem is about using a proxy to let wordpress access internet, not a reverse proxy to access wordpress.
Same problem for me, I've created an image using this simple Dockerfile :

`FROM artifactory.intranet.atih.sante.fr:5003/wordpress:php7.2

RUN apt-get update && apt-get install libcurl4-openssl-dev
RUN docker-php-ext-install curl
`

And I've defined the environment variables WP_PROXY_HOST, WP_PROXY_PORT and WP_PROXY_BYPASS_HOSTS
But it doesn't work

**Comment by yosifkit** [comment]
@bsauvajon, as environment variables they are not specifically looked for by WordPress, you need to add them to `wp-config.php` as PHP variables: https://www.danbishop.org/2013/10/14/using-wordpress-behind-a-proxy/.
