### ISSUE TITLE
FTP access?

### ISSUE THREAD

**Issue by OleksandrKucherenko** [docker-library/wordpress#24]
Can be pre-configured FTP server for wordpress container/image?

**Comment by leon** [comment]
Cant we just add define('FS_METHOD', 'direct'); to wp-config.php?, that way we should be able to install without a hassle...

**Comment by md5** [comment]
The docs on `FS_METHOD` are interesting:

> (Primary Preference) "direct" forces it to use Direct File I/O requests from within PHP, this is fraught with opening up security issues on poorly configured hosts, This is chosen automatically when appropriate.

I wonder that "when appropriate" means. If we could get the normal Wordpress install to think it's "appropriate" to use `FS_METHOD=direct` during the install, that seems more appropriate than modifying `FS_METHOD` in the conf file directly.

**Comment by tianon** [comment]
++ @md5

**Comment by leon** [comment]
another way we could do it is include an optional config file for when you want to overwrite or change some wp-config.php settings. that way you wouldn't have to overwrite the whole file.

```php
if(file_exists('wp-config-ext.php')){
  include_once 'wp-config-ext.php';
}
```

**Comment by md5** [comment]
This would appear to be the relevant code: https://github.com/WordPress/WordPress/blob/eeda68bbda104c5f4f1c837c6bf2288c84027a1d/wp-admin/includes/file.php#L926

As the docs state, `direct` is actually the preferred method. Wordpress does a check to see if a temp file written in `WP_CONTENT_DIR` (i.e. `/var/www/html/wp-content` in this case) has the same ownership as `/var/www/html/wp-admin/includes/file.php`. Since that file is owned by `www-data:www-data` and Apache is running as `www-data`, I'd assume that the `direct` method is actually what this container currently defaults to.

The main case I can think of where it would not allow `direct` as the method is when you've bind mounted in a `wp-content` directory that is not writable by `www-data`.

**Comment by pierreozoux** [comment]
Can we close this issue about FTP? I think the purpose of these images is to be as small as possible. For exotic configuration, you can base you work from this image.

**Comment by nigel-daniels** [comment]
I'm having issues when trying to use the Wordpress importer and using volumes to copy over themes.  To get the wp importer plugin installed I need to use the chown to prevent the request that I use ftp.  However when I mount the Volume to my local file system to copy over a plugin and theme the permissions are changed.  When I unmount the volume the permissions can be chowned back but I no longer see the theme or plugin!  Something is not functioning between the two, I'm not sure what it is.  I was attempting to see if it is possible to ssh into the container to see in detail but was not sure where I find the default information for the container, I'm new to using docker so please point me to the correct location if this is general information not continer specific!

**Comment by pierreozoux** [comment]
@nigel-daniels please open another issue with the right request and ping me, I'll be glad to help (your issue is about rights and not ftp).

To further investigate, you can 'enter' the container by:
`docker exec -it container_name bash`, this will open a bash inside the container (`ls -lat` will probably give you the anser).

@OleksandrKucherenko can you please close the issue, there will never be an ftp service inside this image. If you want ftp, just start an ftp container on the side, and mount wp volumes. Thanks.

**Comment by nigel-daniels** [comment]
@pierreozoux thanks for your advice.  I opened #97 to flag the rights issue.

**Comment by simonh1000** [comment]
> Why do you want to use FTP anyways? It isn't a particularly secure way to transfer files.

One reason would be so that it was easy to update plugins using the wordpress UI

**Comment by tianon** [comment]
The default image configuration should have permissions set so that
WordPress can simply do that properly out-of-the-box, as it prefers to do.

**Comment by simonh1000** [comment]
Yes I discovered that pleasant surprise shortly afterwards
