### ISSUE TITLE
Run the image as non-root user 

### ISSUE THREAD

**Issue by raphaelokon** [docker-library/wordpress#243]
Hi there,

is it possible to run this image as a non-root user inside the container? I tried to `run` it with `www-data` on Docker for Mac but got errors (apache was complaining) in the logs

**Comment by tianon** [comment]
By default it binds to port 80, so trying to run it with `--user www-data` is going to run into https://github.com/moby/moby/issues/8460 unless that port is changed (or one of the other workarounds described there is used, which if your kernel is new enough could be simply `--sysctl net.ipv4.ip_unprivileged_port_start=0`).

**Comment by raphaelokon** [comment]
Thanks @tianon Ah great. So I could just change the bound port inside the container to run as non-root then?

**Comment by tianon** [comment]
Sorry for the delay.

Yes, changing the port is one easy way to accomplish this.  Using `--sysctl net.ipv4.ip_unprivileged_port_start=0` is another.

See also https://github.com/docker-library/wordpress/pull/249 for a bit of functionality the image gained since this was filed which can also be used to trivially switch which user it ends up running as.
