### ISSUE TITLE
Docker-library-bot is slow about pushing updates - Waiting for 4.8.3

### ISSUE THREAD

**Issue by jevonearth** [docker-library/wordpress#247]
Wordpress security release 4.8.3 was released this morning;

https://wordpress.org/news/2017/10/wordpress-4-8-3-security-release/

But there is no docker image available with this release yet.

**Comment by tianon** [comment]
The automated `update.sh` and build test are running right at this very moment: https://doi-janky.infosiftr.net/job/update.sh/job/wordpress/1640/console (which is linked to from the repository `README.md`)

Once that completes successfully, @docker-library-bot will push the commit and I'll make a PR over to https://github.com/docker-library/official-images.

In the meantime, I'd recommend enabling (or leaving enabled, since it's on by default) WordPress's built-in automatic update functionality.

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/3654 :+1:
