### ISSUE TITLE
can't open the wordpress website 8080

### ISSUE THREAD

**Issue by cyril17** [docker-library/wordpress#254]
I follow the doc's steps to do, WordPress can be activated, mysql can, but can not open the website, I replaced the official WordPress image and problem solved, is the  Dockerfile problem ?

**Comment by yosifkit** [comment]
The WordPress image works just fine I just tested the play-with-docker link on the docs which uses the `stack.yml` referrenced [here](https://github.com/docker-library/docs/tree/995f9be8e78db085c96270385d0b788a8a665b65/wordpress#-via-docker-stack-deploy-or-docker-compose).

You'd have to give more detail on how you are launching WordPress like your `docker run` lines or yml file in order to figure out where the problem is.  `docker verison` and `docker info` are also sometime helpful. 
 Since this is not really a problem with the image I would suggest to try [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
