### ISSUE TITLE
Redirect loop @ login page, apache logs look fine

### ISSUE THREAD

**Issue by tannerchung** [docker-library/wordpress#273]
I just created a FRESH local Traefik->Wordpress setup. The Traefik admin and adminer I installed work completely fine and hitting the public wordpress homepage works as well. The problem is when I try to log in it keeps redirecting me back to the login page.

I took a look at the docker logs for the container and it shows this:

```
172.18.0.2 - - [08/Jan/2018:18:12:14 +0000] "GET /wp-login.php?redirect_to=https%3A%2F%2Fwww.example.dev%2Fwp-admin%2F&reauth=1 HTTP/1.1" 200 3380 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.71 Safari/537.36"
172.18.0.2 - - [08/Jan/2018:18:12:27 +0000] "GET /wp-admin/ HTTP/1.1" 302 381 "https://www.example.dev/wp-login.php?redirect_to=https%3A%2F%2Fwww.example.dev%2Fwp-admin%2F&reauth=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.71 Safari/537.36"
```

This is a screen shot of the Network tab in Inspect Element for Chrome:

![screenshot_010818_011802_pm](https://user-images.githubusercontent.com/3707037/34685448-5bb9cf8a-f476-11e7-84e8-8d48ae171fda.jpg)

Everything looks correct so I'm not sure why it keeps redirecting. I should mention I am using https but my self signed cert is working with the other sites, (adminer and traefik dashboard) and I've tried all the tricks already
1. manually created a user through adminer with admin privileges
2. made sure there was an .htaccess file within the root
3. checked the site url's to made sure they're https://www.example.dev
4. edited wp-config.php to have `define('FORCE_SSL_ADMIN', true);` and `$_SERVER['HTTPS'] = 'on';` to the top of the file.
5. double checked my hosts file and it is `127.0.0.1` pointing to www.example.dev

The production site with the same setup works where I can log into the website as well. I don't know if this is the right place to log this issue but I didn't know where else to put it so apologies if this is "off topic".

**Comment by tianon** [comment]
In my experience, this usually happens due to the configured URLs under "Settings" in the WordPress admin interface.  https://codex.wordpress.org/Moving_WordPress has some good tips for moving an existing install between different URLs.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by tannerchung** [comment]
Thanks for directing me!
