### ISSUE TITLE
avoid tar extraction failure if wp-content is bind-mounted read-only

### ISSUE THREAD

**Issue by drzraf** [docker-library/wordpress#281]
Bind-mounting the whole `wp-content` is useful (for plugins, themes, medias, ...), especially if sharing it or testing purpose.
Bind-mounting read-only has its own use (readonly version of the website, development, debugging, ...)

Sadly the current call to tar also extract `wp-content/plugins/akismet` and `wp-content/themes/twenty*`which are, AFAICT, the only upstream directories inside `wp-content`.
These breaks if wp-content is bind-mounted readonly.

Could we think about a way to optionally omit extraction of `wp-content`? (environment?)

**Comment by drzraf** [comment]
#282

**Comment by tianon** [comment]
Sorry for the delay here.  I'm definitely wary about adding more custom logic to our extraction code, especially to make parts of it more optional than they are (we've done a lot of acrobatics to try and make sure it doesn't clobber permissions unnecessarily on bind mounts, for example).

Is there not a smaller set of things you could bind-mount or provide in order to accomplish your goals?

For example, you could have a short `Dockerfile` which simply does something like `FROM wordpress:xxx` followed by `RUN rm -rf /usr/src/wordpress/wp-content` in order to make sure none of `wp-content` even exists _to_ copy.

You could also perform your read-only bind-mount on top of `/usr/src/wordpress/wp-content` instead so that your bind-mounted contents get copied to `/var/www/html` (instead of bind-mounting directly into `/var/www/html`), for example.

**Comment by drzraf** [comment]
I long ago switched to `bedrock`.
