### ISSUE TITLE
Wordpress language return to en_US after container recreation

### ISSUE THREAD

**Issue by luiscoms** [docker-library/wordpress#290]
Hi, I change the language in Settings -> General and recreate container.
After this the language returns to default.

**Comment by luiscoms** [comment]
I just add this funcion on `docker-entrypoint.sh` in order to download language files

```bash
download_language() {
	# download language (https://make.wordpress.org/polyglots/teams/?locale=pt_BR)
	if [ ! -d wp-content/languages ]; then
		if [ -z "${WPLANG:=}" ] || [ "en_US" = "${WPLANG}" ]; then
			echo "Missing WPLANG or default value ${WPLANG}"
			return
		fi
		WP_VERSION=$(cat /usr/src/wordpress/wp-includes/version.php | grep "wp_version =" | cut -d"'" -f2)
		if [ -z "${WP_VERSION}" ]; then
			echo "Could not get WP_VERSION ${WP_VERSION}"
			return
		fi
		echo "Download language ${WPLANG} for ${WP_VERSION}"
		mkdir -p wp-content/languages
		pushd wp-content/languages
		curl https://downloads.wordpress.org/translation/core/${WP_VERSION}/${WPLANG}.zip -O
		unzip ${WPLANG}.zip
		rm ${WPLANG}.zip
		chown -R "$user:$group" .
		popd
	fi
}
```

**Comment by tianon** [comment]
I replicated your steps exactly as described, but after restarting the
container my language was kept just fine. :confused:

Are you sure you preserved the WordPress volume when restarting the
container?

**Comment by tianon** [comment]
So, this is working as designed -- I'd recommend adding an additional entrypoint for your (arguably nonstandard) use-case that contains the language-downloading code you've provided above and having it invoke the image-provided entrypoint when that's finished.

Since this isn't something we're going to officially support directly in the image, I'm going to close, but this thread will serve as a good reference for anyone trying to do something similar in the future.

**Comment by conradkirschner** [comment]
@tianon  could you link this in the readme.md?
