### ISSUE TITLE
Unable to show the content UI when i run application behind the proxy

### ISSUE THREAD

**Issue by JinnaBalu** [docker-library/wordpress#297]
I have dockerized wordpress application with mariadb. It works fine when i run application within the host it works fine.

Issue is when I want to run application in one server and accessing application from the another server with reverse proxy will not work. UI css related files and theme is not working.

Use case : We want to run application in private network where we don't want to open the application directly to the user. We are using reverse proxy to do that job.

**Comment by tianon** [comment]
So if I'm understanding correctly, you installed WordPress without the proxy in place, and then implemented a reverse proxy to sit in front?

Upon install (and during normal usage), WordPress will store a lot of hard-coded references to the exact full URL in which it was initially installed/accessed.  Generally, I would suggest starting with doing the WordPress install directly from the final expected URL so that it embeds the correct strings.  Otherwise, reading through https://codex.wordpress.org/Moving_WordPress is going to be your best bet.

You also want to make sure your reverse proxy is providing an appropriate `Host` header to WordPress, and using `X-Forwarded-For` / `X-Forwarded-Proto` appropriately.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
