### ISSUE TITLE
docker-entrypoint.sh does not consider SSL for MySQL and breaks the install

### ISSUE THREAD

**Issue by msangapu** [docker-library/wordpress#299]
https://github.com/docker-library/wordpress/blob/912d76560ec9e350e24aedd3a30268026082557a/docker-entrypoint.sh#L217

This command will fail for MySQL Servers with SSL enabled - therefore breaks container initialization. Recommend an alternate solution that takes this into account.

**Comment by msangapu** [comment]
If I remove the whole snippet where it creates the database, it installs w/o issue.
This is what I have in my wp-config.php to make use of SSL:

//i have this cert downloaded from https://www.digicert.com/CACerts/BaltimoreCyberTrustRoot.crt.pem earlier in the entrypoint
define('MYSQL_SSL_CA', 'BaltimoreCyberTrustRoot.crt.pem');
define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL | MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT);

**Comment by tianon** [comment]
If your `wp-config.php` already specifies database connection credentials, is there a particular reason you're also specifying them via environment variable (which is what then triggers our database creation attempt)?

**Comment by msangapu** [comment]
Hi @tianon . I'm trying this on a new container that has not been initialized with an empty MySQL server (no databases) with SSL enabled. At this point of the install, the database is not created. I would prefer docker-entrypoint.sh take care of the database creation and consider SSL scenario. Currently it fails as there is no SSL flag specified.

After I stumbled onto this issue, I manually added the credentials into wp-config.php with the defines mentioned above. 

Let me know if you need more info! Also, I'm happy to have a phone conversation if needed.

Thanks!

**Comment by tianon** [comment]
To be frank, since WordPress doesn't really have proper settings for SSL to MySQL, I'm leery of implementing anything extra to support it in our scripts.  At most, I think we should consider updating our documentation to make it clear that if you need SSL for your MySQL connection, you should _not_ set the environment variables we provide and should instead modify `wp-config.php` yourself (perhaps pointing folks to https://core.trac.wordpress.org/ticket/28625 and/or https://wordpress.org/plugins/secure-db-connection/).
