### ISSUE TITLE
Copyed media not shown

### ISSUE THREAD

**Issue by cbirkenbeul** [docker-library/wordpress#314]
Hallo,
i started a wordpress docker container via docker-compose and mounted the wordpress folder to my host. The Container setups wordpress fine and its running all perfectly.
Now i installed plugins and a theme. Runs also perfectly fine.
Next step was to copy my media (mostly picutes) from my old wordpress installation to my folder on my docker host. chown the correct user and permissions and restarted  my wordpress container completely.

Now the problem: i does not see my "old" media. If i upload a new file its located on my docker host in the volume mount, but the copied files are not shown.

Do i have to do something special?
Thx.

**Comment by wglambert** [comment]
Is it overwriting the mounted files from the container startup?

Could you give the commands you used

**Comment by wglambert** [comment]
Closing since this doesn't seem to be an issue with the image

You could also try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
