### ISSUE TITLE
Documentation update: linking containers

### ISSUE THREAD

**Issue by danielbierstedt** [docker-library/wordpress#323]
The documentation suggests to link containers to gain access to a mysql database. Linking containers is marked as deprecated. Could you update the documentation to a different method of suggested connection btw wordpress and the database?

**Comment by wglambert** [comment]
`--link` is more of a "soft deprecation" wherein its usage isn't obsolete, more so that it's surpassed by docker networks in functionality. Using an example for testing container interoperability you can do a `--link` without involving network creation and cleanup. See https://github.com/docker-library/docs/issues/786#issuecomment-350491848

Closing as there are discussions over at https://github.com/docker-library/docs/issues/786, https://github.com/docker-library/docs/pull/1063
