### ISSUE TITLE
Document how to run behind nginx

### ISSUE THREAD

**Issue by morenoh149** [docker-library/wordpress#331]
I had to do quite a bit of digging to make this image run behind nginx. Some issues are related to ssl. Some related to how wordpress requires knowledge of the url it's being served from.

I'd be great to add an example nginx configuration and example of using the `WORDPRESS_CONFIG_EXTRA` environment variable to https://hub.docker.com/_/wordpress/

1) add nginx configuration. Be mindful of https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/ and the code in this container's [wp-config.php](https://github.com/docker-library/wordpress/pull/142#issuecomment-409006361). See also https://codex.wordpress.org/Administration_Over_SSL
```
events {
    worker_connections 768;
    # multi_accept on;
}
http {
    server {
        server_name foo.com www.foo.com;

        location / {
            proxy_pass http://localhost:<your port>;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
```
2) run letsencrypt
3) run image
```
sudo docker run \
-e WORDPRESS_DB_PASSWORD=foo \
-e WORDPRESS_CONFIG_EXTRA="define('WP_HOME','https://foo.com'); define('WP_SITEURL','https://foo.com');" \
--name wordpress \
--link wordpressdb:mysql \
-p <your port>:80 \
-d wordpress
```

My comments at https://github.com/docker-library/wordpress/issues/251#issuecomment-417903011

**Comment by tianon** [comment]
Honestly, I'm not sure I fully understand what makes this a WordPress specific issue?  Setting `X-Forwarded-For` and `X-Forwarded-Proto` when using NGINX in front of a site are pretty common practice, and are _especially_ important when doing TLS termination in NGINX (so that the application has a standardized indication of being served over TLS even though the connection to it is not using TLS).

As for needing `WP_HOME` and `WP_SITEURL`, those should not be required as long as the blog was initially installed with TLS already enabled (or the settings can be updated post-install via the admin panel of the web UI).

**Comment by morenoh149** [comment]
Feel free to close the issue. I just know if I had found these notes it would have saved me 2 days of work. I'm an nginx, docker and wordpress noob.

**Comment by svenyonson** [comment]
This doesn't seem to work if the location is other than `/`. For example:
```
	location /wordpress/ {
		proxy_pass	http://localhost:3280/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            	proxy_set_header X-Forwarded-Proto https;
```
Maybe it is a wordpress specific thing, but `/wordpress` is stripped out of the url on subsequent navigation. For example, after I go through the install GUI and then click `log in`, the url becomes `https://example.com/wp-login.php`, instead of `https://example.com/wordpress/wp-login.php`

**Comment by tianon** [comment]
Correct, that's how WordPress works -- what you'll want to do is run your WordPress container with `WORKDIR` set to `/var/www/html/wordpress` so it knows it is in a subdirectory and acts accordingly.

See https://github.com/docker-library/wordpress/issues/370, https://github.com/docker-library/wordpress/issues/221#issuecomment-356454850, https://github.com/docker-library/wordpress/pull/133#issuecomment-383199445.

**Comment by svenyonson** [comment]
Thanks for the quick response - do I do that with -e WORKDIR or -e WORDPRESS_CONFIG_EXTRA=define(WORKDIR...?

**Comment by tianon** [comment]
If you're doing "docker run", that'd be "-w" / "--workdir"

**Comment by svenyonson** [comment]
Hmmm. Now I get a 404 on `https://youvegotmouse.com/wordpress/wp-login.php`

    # virtual host file location entry

	location /wordpress/ {
		proxy_pass	http://localhost:3280/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            	proxy_set_header X-Forwarded-Proto https;

	}

    # docker

	docker run \
	-e WORDPRESS_DB_PASSWORD=password \
	-e WORDPRESS_CONFIG_EXTRA="define('WP_HOME','https://youvegotmouse.com/wordpress/'); define('WP_SITEURL','https://youvegotmouse.com');" \
	--name wordpress.youvegotmouse \
	--link db.youvegotmouse:mysql \
	-v "/var/www/youvegotmouse/wordpress":/var/www/html \
	-p 3280:80 \
	-w /var/www/wordpress \
	-d wordpress

**Comment by bukowa** [comment]
https://github.com/docker-library/wordpress/issues/251#issuecomment-576405899
