### ISSUE TITLE
How to increase max upload file size on Google Cloud Kubernetes Click To Deploy

### ISSUE THREAD

**Issue by giulianopires** [docker-library/wordpress#374]
I'm new to Kubernetes and I'm in trouble.
After installing Wordpress on Kubernetes with the solution provided by Google Click to Deploy Containers I can not modify the file upload limit for Wordpress. I've seen some cases that need to create an upload.ini file, however I do not even know how to do it.
Can anyone help me with clear and easy step by step?

**Comment by wglambert** [comment]
https://github.com/docker-library/wordpress/issues/10#issuecomment-66906071

**Comment by wglambert** [comment]
Closing since this issue looks resolved

If you have further questions you should ask [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). As these repositories are for issues with the image and not necessarily for questions of usability
