### ISSUE TITLE
Publish tag for wordpress 4.9.10

### ISSUE THREAD

**Issue by ncpierson** [docker-library/wordpress#399]
I expect there will be a lot of demand for staying on version 4.X. Can we continue pushing tags?

[Version 4.9.10](https://wordpress.org/support/wordpress-version/version-4-9-10/) was released in March 2019, and it would be great if there were a docker image tag for it.

Thanks!

edit: looks like 4.9.9 is also missing

**Comment by yosifkit** [comment]
We only publish the versions that are officially supported by WordPress (which is just the latest):

> The only current officially supported version is WordPress 5.1.1. Previous major releases before this may or may not get security updates as serious exploits are discovered.
>
> \- https://codex.wordpress.org/Supported_Versions

WordPress oddly issues updates for versions that they have long since stopped supporting (`3.7.x` and above were also [updated in march](https://wordpress.org/download/releases/)).

Since WordPress will auto-update for non-major bumps, you should be able to use the `wordpress:4.9` tag and just let the updates happen to get `4.9.10` (assuming you keep the persistent volume that it writes the wordpress source to)

**Comment by ncpierson** [comment]
@yosifkit Yeah, I used `4.9.8` and everything worked perfectly. Thanks!
