### ISSUE TITLE
stack.yml / docker-compose.yml vs volumes

### ISSUE THREAD

**Issue by jol64** [docker-library/wordpress#404]
The example .yml at https://hub.docker.com/_/wordpress does not use any volumes external to the containers. I think it is best practice to externalize any data or configuration from a container, in order to avoid date or confiugration being lost during an update to a newer version.
Can you please update instructions?
Thanks, Joachim

**Comment by tianon** [comment]
Since this image defines a `VOLUME`, `docker-compose` has some automatic behavior that helps here, but I agree that especially for Swarm it makes sense to update that example to include an explicit volume. :+1:

(It lives in https://github.com/docker-library/docs/blob/ad98a4b6f83dd5182b106c2c3146e596bb0b439b/wordpress/stack.yml if you wanted to take a stab at it!)
