### ISSUE TITLE
Error on install plugin theme wordpress in docker

### ISSUE THREAD

**Issue by PhilipRamkeerat** [docker-library/wordpress#422]
I am trying to create a wordpress application through docker, but the plugins are not being installed:

```
Installing Plugin: WPBakery Visual Composer
Baixando pacote de instalação a partir de http://localhost:2000/wp-content/themes/altius/fastwp/plugins/js_composer.zip…

Falha no download. cURL error 7: Failed to connect to localhost port 2000: Connection refused
```

I researched and still haven't found help for this question, does anyone know anything about it?

**Comment by wglambert** [comment]
You should be able to mount or `curl` the `js_composer.zip` onto the image and then in the wordpress ui just upload it from the container's own storage
https://kb.wpbakery.com/docs/getting-started/plugin-installation/

Did you have anything configured to use port 2000? That port is officially registered to [Cisco Skinny Client Control Protocol (SCCP)](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Registered_ports) which probably isn't what `curl` is trying to communicate with

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
