### ISSUE TITLE
How to change File Permissions

### ISSUE THREAD

**Issue by kenkoii** [docker-library/wordpress#438]
I'm using a plugin to generate backups for migrating/exporting my wordpress multisite, but I'm running into an error which is related to permissions and their support led me to this document in the plugin's knowledge base. https://help.servmask.com/knowledgebase/invalid-file-permissions/

How can I apply such permissions? In my local environment, I am using docker-compose and it works fine but for our deployment we are using ECS and I cannot get it to work, I have tried adding such lines to my Dockerfile:

```
# Add write permission to wordpress directory
RUN usermod -u 1000 www-data
RUN chown -R www-data:www-data /var/www/html
RUN find /var/www/html -type d -exec chmod 777 {} \;
RUN find /var/www/html -type f -exec chmod 644 {} \;
RUN find /var/www/html -type f -group 'www-data' -exec chmod g+rw {} \;
RUN find /var/www/html -type d -group 'www-data' -exec chmod g+rw {} \;
```

I still get the same message. SSH-ing to my container instances and changing permission on by oner is not an option since I have many containers running. 

Can anyone point me to the right direction? Any help is appreciated.

**Comment by wglambert** [comment]
What about making the folders and giving those 777 permissions
`/wordpress/wp-contents/ai1wm-backups`
`/wordpress/wp-content/plugins/all-in-one-wp-migration/storage`

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
