### ISSUE TITLE
Getting 'AH01630: client denied by server configuration'

### ISSUE THREAD

**Issue by MihaMarkic** [docker-library/wordpress#443]
For no apparent reason, out of the blue, my website started giving 404s for everything.
Looking at docker logs it says something like:

> AH01630: client denied by server configuration: /var/www/html/

I'm using latest wordpress image.
I tried even removing the "deny all" entry in apache2.conf but it doesn't change. Any idea what could be causing it?

**Comment by wglambert** [comment]
https://github.com/docker-library/php/issues/258 might be the same

Are you using multiple virtual host configs?

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by MihaMarkic** [comment]
@wglambert I use single host. I suspect now that there is something wrong with .htaccess file.

**Comment by MihaMarkic** [comment]
Somebody messed with iThemes Security plugin (unbeknown to me) I think, or another (disabling all plugins did the trick).
