### ISSUE TITLE
how to setting only using hostname to visit ?

### ISSUE THREAD

**Issue by powersee** [docker-library/wordpress#446]
I try to use caddy proxy the 8080 port to my domain , but it did not work.

So i try to edit the apache.conf , but there didn't has vi ...

So i want to know how i can set only using hostname to visit my blog .

**Comment by wglambert** [comment]
I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

[This post ](https://skippy.net/caddy-docker-php-wordpress/) looked like a good resource on using Caddy with WordPress
