### ISSUE TITLE
How to modify Apache tuning parameters?

### ISSUE THREAD

**Issue by ricxsar** [docker-library/wordpress#447]
I'm creating my custom `Dockerfile` based on the official image for personal use case. I need to modify some parameters (from this [page](https://httpd.apache.org/docs/2.4/mod/mpm_common.html)) for tuning purposes. 

How should I do it?

I have noticed this [line](https://github.com/docker-library/wordpress/blob/41af7e24571774b8016b930bfb767c39552d0a02/php7.2/apache/Dockerfile#L94-L96) which modifies the logging format. Maybe we can do the same.

**Comment by wglambert** [comment]
I think you pick an mpm module from here https://httpd.apache.org/docs/2.4/mpm.html and then edit it
>At the user level, MPMs appear much like other Apache httpd modules. The main difference is that one and only one MPM must be loaded into the server at any time. 

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by ricxsar** [comment]
Thank you for responding.  I'm using the same Apache base image, Prefork i believe.
I am aware of editing some configuration but I not familiar with linux commands to do the job at the docker image level. Eg. `MaxConnectionsPerChild` is defaulted to `zero`. Documentation says:

> Setting MaxConnectionsPerChild to a non-zero value limits the amount of memory that process can consume by (accidental) memory leakage.

Reference: https://httpd.apache.org/docs/2.4/mod/mpm_common.html#maxconnectionsperchild

Do you have any plans on creating image for different MPM modules?

I will try to ask on the suggested websites.

**Comment by yosifkit** [comment]
Since the apache variant is based on the `php:[version]-apache` image, you can use the [Docker Hub docs for php](https://github.com/docker-library/docs/tree/9bdb7f1469737a9c7359853534f8819e0e34b1da/php#changing-documentroot-or-other-apache-configuration).  So, either edit or add conf files somewhere in `/etc/apache2/`, just like a regular Debian install.

**Comment by ricxsar** [comment]
I was able to solve it myself adding:
```
RUN set -eux; \
# see https://aws.amazon.com/premiumsupport/knowledge-center/504-error-classic/
	{ \
		echo 'AcceptFilter http none'; \
		echo 'AcceptFilter https none'; \
	} > /etc/apache2/conf-available/disable-tcp-accept-defer.conf; \
	a2enconf disable-tcp-accept-defer;

RUN set -eux; \
	sed -i 's|KeepAliveTimeout 5|KeepAliveTimeout 95|' /etc/apache2/apache2.conf;
```

Which modifies the setting for the AWS ALB to be happy.

**Comment by wglambert** [comment]
Cool glad you got it figured out, gonna close the issue then since it's resolved

If you had other questions about using the images you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). You'd probably get more people looking at your question
