### ISSUE TITLE
Getting file ownership correct for development

### ISSUE THREAD

**Issue by katsar0v** [docker-library/wordpress#464]
I am using `wordpress:5.3.2-php7.4-fpm-alpine` from dockerhub and am having the following small problem:
I have the folder `wp/` which I have mounted to the container (`/var/www/html`). After WordPress is downloaded the files and folders within are owned by `www-data`, the problem is that I cannot edit files or create new folders inside `wp/` on my host system. My current temporary solution is to run `sudo chmod 777 wp --recursive` (but we all know that 777 is a bad practice). Is there a good development setup for this image, which I can use for developing themes and plugins? 

PS: I found out that if I have `www-data` group on the host system with the same system as in the container, it works normally, but this has to be done manually.

**Comment by wglambert** [comment]
Setting 774 permissions would allow the owner and group full access while everyone else only has read access, so adding your host-user to the www-data group is an ideal solution for proper permissions

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by yosifkit** [comment]
Since the WordPress image is based upon the PHP image, you should be able to just run it as your user id:
https://github.com/docker-library/docs/tree/0c91525d68b1800e1a6be673ba0a0e465f3445ef/php#running-as-an-arbitrary-user

**Comment by katsar0v** [comment]
@wglambert thanks, that's not really helpful but I will try there

@yosifkit how can I adjust the uid and gid of `www-data` in php-fpm images? I see only apache variables there

**Comment by tianon** [comment]
Last sentence of his linked section:

> For running the FPM variants as an arbitrary user, the `--user` flag to `docker run` should be used (which can accept both a username/group in the container's `/etc/passwd` file like `--user daemon` or a specific UID/GID like `--user 1000:1000`).

**Comment by katsar0v** [comment]
I must have skipped that! Thanks!
