### ISSUE TITLE
cURL error 60: SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by jcubic** [docker-library/wordpress#469]
When I tried to update Wordpress I've got this error:

```
Download failed.: cURL error 60: SSL certificate problem: self signed certificate in certificate chain
```

How can I fix it? This is docker image so it don't have any extra files besides what inside the docker. I run this app from external IP address that is local IP for private OpenStack cloud.

**Comment by wglambert** [comment]
I would ask over at a WordPress resource or the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't a user-help forum

Google has a number of results for this error, usually involving upgrading plugins
www.google.com/search?&q=Download+failed.%3A+cURL+error+60%3A+SSL+certificate+problem%3A+self+signed+certificate+in+certificate+chain

**Comment by jcubic** [comment]
Asked on Docker forum https://forums.docker.com/t/how-to-get-access-to-php-ini-to-fix-wordpress-curl-ssl-error/88790

I think that this is the bug docker image for wordpress just work, and it should work the same on every machine.

Most Google results show that this is issue with curl so it image should never work, because solution is to add one file with curl CA. Also there is no way to apply the patch suggested in those google results because wordpress image don't have php.ini file, I've tried add to upload.ini file the line suggested as a fix and don't work.

**Comment by bukowa** [comment]
@jcubic you can use https://www.php.net/manual/en/configuration.file.per-user.php

**Comment by yosifkit** [comment]
So it sounds like you have a corporate proxy with a self signed cert that you need to inject into the image so that it can trust it when doing wordpress updates via the interface.

If you just need to add an `ini` for php, there is a whole `conf.d`directory. I think you should be able to just drop one in there.

```console
$ docker run -it --rm wordpress bash
root@45829822cce0:/var/www/html# find / -name '*.ini'
/usr/local/etc/php/conf.d/error-logging.ini
/usr/local/etc/php/conf.d/opcache-recommended.ini
/usr/local/etc/php/conf.d/docker-php-ext-exif.ini
/usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini
/usr/local/etc/php/conf.d/docker-php-ext-zip.ini
/usr/local/etc/php/conf.d/docker-php-ext-gd.ini
/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
/usr/local/etc/php/conf.d/docker-php-ext-imagick.ini
/usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini
/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
```

**Comment by jcubic** [comment]
OK, this is no issue, was installing CA certs that my corporate have for their certs I was using wrong files (I was using bitbucket and downloaded files using view RAW and Save As and the content of the files was bitbucket login page, instead of actual cert).

So the solution was (just if someone have same issue):

I've put my certs into directory and in docker-compose I've added volume:
```
   volumes:
      - ./html:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./ca:/usr/local/share/ca-certificates/ca
```

and running:
```
docker exec -it $(docker container ps | grep wordpres | cut -f1 -d' ')  update-ca-certificates
```
it updated ca certs in container.

**Comment by jcubic** [comment]
Simple solution is to just build docker image with cert, I have to install one tool on top of wordpress (for emails) so I've just added the certs and run the update while building an image.
