### ISSUE TITLE
Unable to upload large images

### ISSUE THREAD

**Issue by siddjain** [docker-library/wordpress#483]
we are using the `wordpress:7.4php-fpm-alpine` image and have created an `uploads.ini` file as described in

https://github.com/docker-library/wordpress/issues/10

Our exact file is this:

```
# cat /usr/local/etc/php/conf.d/uploads.ini
file_uploads = On
memory_limit = 500M
upload_max_filesize = 100M
post_max_size = 100M
max_execution_time = 600
max_file_uploads = 50000
max_execution_time = 5000
max_input_time = 5000
```

With this file the upload page says Maximum upload file size: 100 MB. But when we try to upload large file (still less than 100MB) it fails with

413 (Request Entity Too Large)

How can we fix this? We are also running a `nginx` container in case it makes any difference.

**Comment by wglambert** [comment]
That's an http error so it's exhibited by nginx

These should help
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
https://www.tecmint.com/limit-file-upload-size-in-nginx/

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by siddjain** [comment]
Thanks. That was the problem.
