### ISSUE TITLE
Process for upgrading

### ISSUE THREAD

**Issue by neilbags** [docker-library/wordpress#491]
What is the process to upgrade wordpress when using this image? 

Is it safe to just upgrade using wordpress's updater, or should I pull a new docker image, recreate the container, then run the updater? 

Is this process documented, and is there an automated way to know when your running images are affected by CVEs?

**Comment by wglambert** [comment]
The built-in auto update functionality is the recommended way

We don't have anything in the documentation about it, as it doesn't really differ from upstream's documentation on upgrading https://wordpress.org/support/article/updating-wordpress/#one-click-update

As for CVE's we have a section in the FAQ https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves
I don't have any recommendations for automated scanning you'll have to search around, there's a number of options

In the future questions like these should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by neilbags** [comment]
Thanks for that. I know that other apps with auto-updaters (e.g. nextcloud) break if container images aren't updated before running the auto updater so I wanted to check this specifically before putting this into production.
