### ISSUE TITLE
Stop generating Wordpress files after docker-compose up

### ISSUE THREAD

**Issue by trenccan777** [docker-library/wordpress#492]
Is it possible to stop generating wordpress core installation files on host volume path after I run `docker-compose up -d` ?

**Comment by tianon** [comment]
Can you be more specific about what you're trying to accomplish?  If you're referring to the "copy Wordpress into the volume" behavior, that only happens if we are reasonably confident it does not already exist:

https://github.com/docker-library/wordpress/blob/8215003254de4bf0a8ddd717c3c393e778b872ce/docker-entrypoint.sh#L48

Additionally, given this is a question on usage, you'd probably have more luck starting a conversation on [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by farynam** [comment]
About this copying wp files what is the reason of this in runtime ? At the end I get bunch of Wordpress files in the root directory like that:

`root@62d775de43a7:/# ls -1
bin
boot
dev
etc
home
index.php
lib
lib64
license.txt
media
mnt
opt
proc
readme.html
root
run
sbin
srv
sys
tmp
usr
var
wp-activate.php
wp-admin
wp-blog-header.php
wp-comments-post.php
wp-config-sample.php
wp-content
wp-cron.php
wp-includes
wp-links-opml.php
wp-load.php
wp-login.php
wp-mail.php
wp-settings.php
wp-signup.php
wp-trackback.php
xmlrpc.php
`

**Comment by yosifkit** [comment]
@farynam, that sounds like you changed the working directory to `/` (`-w` on `docker run`). The copy in the entrypoint script just puts it into the current directory.

**Comment by richardboydnz** [comment]
This seems to be a common complaint. What is the purpose of a '5-minute install' in a production image? It is just dangerous. There was a request for this behaviour to be optional via a simple environment variable which was closed for some reason. https://github.com/docker-library/wordpress/pull/282

I'm currently having to hack my own dockerfile wordpress image to prevent this behaviour so that it doesn't overwrite my production wordpress sites on restart. I have no idea how much of the wordpress image I've disabled as I'm not a docker guru. This should not be required to disable a feature that is very unusual in docker images.

It would be great to have a production version of the wordpress image with the important settings and php extenstions but without the unusual stuff that wants to rewrite my websites. 5.5.1-php7.2-fpm-install vs 5.5.1-php7.2-fpm-production ?

If this already exists elsewhere I would love to know about it.

**Comment by tianon** [comment]
https://github.com/docker-library/wordpress/issues/246#issuecomment-340557707:

> ... the entire _install_ is considered by upstream to be mutable state -- WordPress expects to self-update (and IMO anyone who doesn't allow it to do so these days is asking for trouble), so we simply recommend that users instead make the entire install a directory and be done with it.

**Comment by tianon** [comment]
Closing, since this is by design.

For further help/discussion, I'd suggest a dedicated support forum, such as [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
