### ISSUE TITLE
Permalinks need to be resaved after redeploying the container. 

### ISSUE THREAD

**Issue by tnielsen2** [docker-library/wordpress#495]
I am running this container in AWS ECS, on EC2. I am mounting the entire `wp-content` folder into the container as a volume. The database is hosted on RDS.

Whenever I redeploy a container I get 404 errors on every page but the main page.  I have to log into `wp-admin` --> Settings --> Permalinks --> Save to fix the issue. This occurs every time the container is refreshed in a deploy scenario, or if the container fails.

Adding a flush_rewrite() to the code doesn't seem to fix the issue either. 

Has anyone run into this and if they have, what is the fix? I do not see anything in the `docker-entrypoint.sh` script that would cause this. 

Thanks in advance!

**Comment by wglambert** [comment]
Is there anything in the `docker logs` that shows an error of some kind about the issue?

**Comment by tianon** [comment]
I think this is more of a quirk of how Wordpress is designed, right?  In my experience, it ends up saving a *lot* of full URLs throughout the database.  I believe `wp-cli` has a subcommand that can help to convert them from one URL to another?

**Comment by tnielsen2** [comment]
No docker logs that show any issue.

I attempted to install wp-cli into the container, and adding a task to flush the permalinks in the entrypoint script.

`wp rewrite flush --allow-root && wp rewrite structure '%postname%' --allow-root && wp rewrite list --format=csv --allow-root`

This results in "successful" messages, however it still does not "work".

What I have found, is that if I visit the permalinks settings page (without saving it), it "starts working", in that those pages no longer get 404 errors. It is almost as if visiting the permalinks settings page "does the trick".

**Comment by tnielsen2** [comment]
I have this resolved. The container has a clause in the entrypoint that detects `index.php` and `wp-includes/version.php`. After removing those files from my volume mount and restarting the container this seemed to fix the problem. It had something to do the .htaccess file being created dynamically by the script (although the permissions were correct).

After allowing the entrypoint script to run and create these files, it seems to be resolved. Unusual, and I still don't understand exactly why, but it is fixed now.

Thanks for the quick responses!

**Comment by hajdi-k** [comment]
I wasted a lot of time on this so I'll share what the problem was in my case, hope it helps somebody.

The Dockerfile was creating a .htaccess file (search for code like  `echo 'RewriteEngine On'; \` ).

When I register a new post type and rewrite the url like [this](https://wordpress.stackexchange.com/a/53305):
`$args = array(    ...    'rewrite'  => array('slug' => 'fancy_apples')   ...   ); register_post_type('apples', $args);`
then as expected, I need to visit and save permalinks. But this is done only once manually, or on theme activation.

But when I added a rewrite rule with add_rewrite_rule, I had to re-visit the permalinks page after every deploy. Note that I didn't even have to save the permalinks, just visiting the page was enough.

So in the end I realized that, after I visit the permalinks page, more lines are added in the container's .htaccess file, based on the rewrite rule.
So every time the container is re-deployed, the shorter .htaccess from the image overwrites the changes that happened when I visit the permalinks page.

The fix was to add the rewrite rules to .htaccess directly, instead of going through WPs add_rewrite_rule. However this "fix" is not useful if you have plugins that use add_rewrite_rule or if different themes have it. 

Still, at the core, the issue is that the .htaccess file gets overwritten in the Dockerfile, so the correct approach might be to pass the .htaccess to the container instead of it generating it on it's own.
