### ISSUE TITLE
php access to protected files

### ISSUE THREAD

**Issue by rventura** [docker-library/wordpress#500]
PHP inside the container seems to be able to run php files, even when they are fully protected (i.e., chmod 000 xpto.php). Unclear why this happens since PHP reports being run as user www-data. while only root should be able to open chmoded-000 files.

**Comment by tianon** [comment]
I'm not able to reproduce? :confused:

```console
$ docker pull wordpress
Using default tag: latest
latest: Pulling from library/wordpress
Digest: sha256:7a0ae0f2bf8cbbaa6d439ebaefa5c8545645d1457bab5dec7ee65ab9b5db1c79
Status: Image is up to date for wordpress:latest
docker.io/library/wordpress:latest

$ docker run -dit --name test wordpress
104c4b6c227e68388dcf750b471dfe9c85977b2f80d27d40d85e4e89e5b0496d

$ docker exec -it test bash
root@104c4b6c227e:/var/www/html# echo '<?php echo "hi";' > test.php
root@104c4b6c227e:/var/www/html# chmod 000 test.php 
root@104c4b6c227e:/var/www/html# curl -f localhost/test.php
curl: (22) The requested URL returned error: 500 Internal Server Error
```

Do you have a simple reproducer we could use to try and track this down?

**Comment by rventura** [comment]
After the commands you showed, I tried this:

root@c1d5657a9724:/var/www/html# echo '<?php echo "hi\n"; ?>' > t1.php
root@c1d5657a9724:/var/www/html# cp t1.php t2.php
root@c1d5657a9724:/var/www/html# curl -f localhost/t1.php
hi
root@c1d5657a9724:/var/www/html# chmod 000 t1.php t2.php
root@c1d5657a9724:/var/www/html# curl -f localhost/t1.php
hi
root@c1d5657a9724:/var/www/html# curl -f localhost/t2.php
curl: (22) The requested URL returned error: 500 Internal Server Error

Shouldn’t both URLs give 500 after both being chmod’ to 000?

Thanks,
Rodrigo

**Comment by tianon** [comment]
That's probably due to `opcache`; once PHP loads `t1.php`, it caches that result.  You'll see something similar if you use something like `<?php echo 'hi';`, then replace it with `<?php echo 'foo';` after you've loaded it once (it will still say "hi" instead because `mod_php` serves from the cached version of the parsed file until the cache expires).

**Comment by rventura** [comment]
I tried a similar thing in Alpine+apachew+php7 and the result looks ok:

```
/var/www/localhost/htdocs # echo '<?php echo "hi\n" ?>' >t1.php
/var/www/localhost/htdocs # curl -f localhost/t1.php
hi
/var/www/localhost/htdocs # cp t1.php t2.php
/var/www/localhost/htdocs # chmod 000 t1.php t2.php
/var/www/localhost/htdocs # curl -f localhost/t1.php
curl: (22) The requested URL returned error: 500 Internal Server Error
/var/www/localhost/htdocs # curl -f localhost/t2.php
curl: (22) The requested URL returned error: 500 Internal Server Error

```
Why does it show a different behavior?

Rodrigo

**Comment by tianon** [comment]
Probably because you don't have `opcache` installed and/or enabled.

**Comment by wglambert** [comment]
Closing since this seems resolved, you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
