### ISSUE TITLE
How can I redirect outbound traffic to port 80?

### ISSUE THREAD

**Issue by crechberger** [docker-library/wordpress#501]
Hi,

I'm using the WordPress Plugin WP2Static to create a static version of my WordPress site, but unfortunately it doesn't work as expected, because the plugin inside the container wants to cURL the domain of the WordPress site and receives "Failed to connect to www.example.org port 443: Connection timed out".

My setup on the server contains a reverse proxy container that redirects all traffic from outside to the WP container. 
In the "settings" of the WP backend the domain is set to www.example.org, but I suspect that once the container tries to cURL www.example.org, it doesn't know that it should actually get redirected to port 80 inside the container. So my question is, how can I create such a redirect within the WP Docker image - since iptables is not installed and it can't be installed using sudo?

I am using the docker image wordpress:5.4.1-php7.3.

Your help is appreciated :)

**Comment by wglambert** [comment]
https://docs.docker.com/config/containers/container-networking/#published-ports

Our example docker-compose.yml forwards 8080 on the host to 80 in the container which Apache is configured to listen on
https://github.com/docker-library/docs/tree/master/wordpress#-via-docker-stack-deploy-or-docker-compose

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by yosifkit** [comment]
You should be able to use `--add-host=www.example.com:127.0.0.1`, but since it is trying to hit https you may need to point it to the reverse proxy that is doing the ssl termination.

https://docs.docker.com/engine/reference/run/#network-settings

**Comment by crechberger** [comment]
Thank you, that already helped.
