### ISSUE TITLE
How to print to the docker logs/stdout/stderr from php?

### ISSUE THREAD

**Issue by dave-dm** [docker-library/wordpress#508]
I've googled thoroughly but nothing seem to be working, `file_put_contents('/var/log/apache2/error.log')` doesn't work, ` fopen('php://output')` doesn't work, `STDOUT` is not defined, `error_log()` doesn't work either. I'm just trying to debug some php code and see the output in the docker/apache console.

**Comment by wglambert** [comment]
This might help? https://github.com/docker-library/php/issues/811#issuecomment-481029692

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
