### ISSUE TITLE
No table prefix

### ISSUE THREAD

**Issue by TiagoGouvea** [docker-library/wordpress#516]
I'm importing a database from a wordpress database without any prefix, the users table is just `users`.

I tried `WORDPRESS_TABLE_PREFIX: ` and `WORDPRESS_TABLE_PREFIX:  ''` but in still trying to access `wp_users`.

There exists an easy way to work like that?

Thanks

**Comment by wglambert** [comment]
From the WordPress bug reports an empty table prefix doesn't seem supported https://core.trac.wordpress.org/ticket/41250#comment:1
https://core.trac.wordpress.org/changeset/13853 
https://core.trac.wordpress.org/browser/trunk/wp-admin/setup-config.php?rev=13853#L160

**Comment by tianon** [comment]
Indeed, and if this _is_ possible/supported, this is something you'll have to do via either the interactive installation wizard, or via doing the modifications to `wp-config.php` yourself (because as you've surmised, our script doesn't differentiate between unset and empty, and it's somewhat difficult to do so in pure shell script).

**Comment by TiagoGouvea** [comment]
Ok. I did it, accessed the container and changed manually on file.

Thanks.
