### ISSUE TITLE
Too Many Redirect when activate a Multilanguage plugin

### ISSUE THREAD

**Issue by ftp21** [docker-library/wordpress#517]
Hello,
I setup a Wordpress simple container but when i try to enable a plugin for multilanguage like Polylang or WPML i receive a TOO_MANY_REDIRECTS error.

No php error shown on the docker log.

Which log can i attach to help for fix the issue?

**Comment by wglambert** [comment]
I'm able to install and enable Polylang just fine

![image](https://user-images.githubusercontent.com/26428991/87834147-8ac64a80-c83e-11ea-9aba-f28a53bda265.png)

![image](https://user-images.githubusercontent.com/26428991/87834171-9e71b100-c83e-11ea-89fe-8b8a723fc924.png)

I used the example `docker-compose.yml` from https://github.com/docker-library/docs/tree/master/wordpress#-via-docker-stack-deploy-or-docker-compose

You could try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by yosifkit** [comment]
You'll probably want to provide them with more detail as well, like which exact wordpress image and if there are any other services involved in the http path, maybe a reverse proxy like nginx.

Since the image is working fine, I'll close.
