### ISSUE TITLE
No language selection when using host dir

### ISSUE THREAD

**Issue by suchja** [docker-library/wordpress#52]
I'm using the latest official mysql and wordpress images with boot2docker on my Mac. They are started in normal way. When I use the wordpress image to start a container without mount-bind /var/www/html/ to any other container or host directory everything works as expected. During startup of the wordpress container a wordpress installation is done and when I access the page the first time I do see install screen with the language selection.
However, as soon as I do mount-bind the /var/www/html/ directory to an empty host dir (e.g. -v $(pwd):/var/www/html/ ), I do get the install screen, but without the language selection.
It seems that in both cases the wordpress instance works fine, but I would like to have it not in English.

Any thoughts?

Jan

**Comment by yosifkit** [comment]
I am not able to replicate in linux.  It could have something to do with the file sharing between the host mac and the boot2docker vm which uses the vbox guest additions.  Here is what I did:

```console
$ docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=qwerqwer -d mysql
$ docker run --name wordpress-instance --link some-mysql:mysql -p 8080:80 -d -v /tmp/wp:/var/www/html wordpress
# then opened a browser to localhost:8080 and got the language selection screen.
```

Have you been able to find anything more out?

**Comment by md5** [comment]
@yosifkit /tmp will be on the VM's local filesystem in a b2d scenario. Only
/Users is mounted via vboxsf.

**Comment by yosifkit** [comment]
Yeah, but it doesn't matter what I mount on my linux system;  I was just testing that there wasn't some strangeness when using a bind-mount.  It seems like there is something happening with the vbox share but I don't have a mac to test and it could be really a boot2docker issue and not really a problem in the image.

**Comment by md5** [comment]
I was able to reproduce this on my Mac under b2d.

There are a few things going on here, but the bottom line is that Wordpress checks to see if it can modify `/var/www/html` during the installation. When it sees that it can't, it doesn't provide the option to install the language packs.

**Comment by md5** [comment]
Just to see if it would work, I unmounted `/Users` inside the b2d VM and remounted it with the uid and gid of `www-data`:

    boot2docker ssh
    sudo umount /Users
    sudo mount -t vboxsf -o defaults,uid=33,gid=33 Users /Users

Once I did that, I was about to do a bind mount from a host directory to `/var/www/html` and have Wordpress correctly show the language installation dialog.

**Comment by suchja** [comment]
@md5 tried the same as you suggested and this works like a charm now. Would you expect any other issues when using it with the changed uid and gid? Do you think I should file an issue with b2d, or will it be solved with php:Apache as you referenced?

THANKS!

**Comment by md5** [comment]
The default situation in boot2docker is that the `/Users` mount is owner by the uid and gid of the `docker` user in the VM (i.e. `docker:staff` or `1000:50`). Given the typical permissions on directories and files, this means that only root or a user with uid 1000 inside the container can write to that mount.

If you change the uid on the mount from `1000` to `33`, that means that uid `33` inside the container is able to write to the mount instead of uid `1000`. Unless you were relying on uid `1000` having access previously, there should be no negative repercussions to changing the uid of the `/Users` mount. The only other thing that would be affected is that the `docker` user in the VM will no longer be able to access the `/Users` mount, but I can't think of any reason that would be needed (plus `docker` has full `sudo` in the VM if it really needs to access the mount).

As for which fix is preferable, I'd probably say that being able to change the UID that `php:apache` runs as is the more broadly useful change. I can't see b2d changing the uid of that mount to `33` just to accommodate people trying to mount `/var/www/html` into their containers.

**Comment by suchja** [comment]
I also did not find any problems so far. However, I reverted back and now using a separate data only container which gets properly backup'd and avoid using host volumes for the time being.

Do I need to close this issue here? Sorry for the question, but it's my first issue on github. I generally don't like to have open issues floating around, but I'm not really sure on the usual workflow here.

**Comment by yosifkit** [comment]
It sounds like we found the problem and a workaround.  I will go ahead and close the issue.  Next time feel free to close the issue if you feel that your question is solved (at least in docker-library/ and docker/, not sure about other projects on github)

**Comment by md5** [comment]
I did play around a bit with `fmode` and `dmode` on the `vboxsf` mount, for posterity's sake. It might be worth some investigation in b2d to change how that mount works. Then again, it may be  a `machine` thing, though I don't think it supports the `/Users` thing yet, even in the VirtualBox driver.

**Comment by md5** [comment]
Or perhaps I spoke too soon? https://github.com/docker/machine/blob/d38216b399188ec858a909830dac5a93d00fea20/drivers/virtualbox/virtualbox.go#L282

**Comment by tianon** [comment]
I was going to say, it darn well better -- I wrote that code. :wink:
