### ISSUE TITLE
Fatal error: Uncaught Error: Class 'mysqli' not found in Standard input code:22

### ISSUE THREAD

**Issue by silviubogan** [docker-library/wordpress#525]
When running first time `$ docker-compose up` I get these and just these messages regarding the `wordpress:latest` container:

```
wordpress_1   | 
wordpress_1   | Fatal error: Uncaught Error: Class 'mysqli' not found in Standard input code:22
wordpress_1   | Stack trace:
wordpress_1   | #0 {main}
wordpress_1   |   thrown in Standard input code on line 22
wordpress_1   | 
wordpress_1   | WARNING: unable to establish a database connection to 'db:3306'
wordpress_1   |   continuing anyways (which might have unexpected results)
wordpress_1   | 
wordpress_1   | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.27.0.4. Set the 'ServerName' directive globally to suppress this message
wordpress_1   | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.27.0.4. Set the 'ServerName' directive globally to suppress this message
wordpress_1   | [Sat Aug 22 13:36:36.724584 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.15 configured -- resuming normal operations
wordpress_1   | [Sat Aug 22 13:36:36.725271 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

How can I avoid this? I think it is an issue in the wordpress image because I used older versions of this image and they did not complain like above (although I used MySQL 5.7 and not MariaDB in the past). I think that ideally the wordpress image would include mysqli.

Thank you.

**Comment by tianon** [comment]
I'm a bit confused here; we *do* include `mysqli` in the image we maintain/distribute:

```console
$ docker pull wordpress
Using default tag: latest
latest: Pulling from library/wordpress
Digest: sha256:6da8f886b20632dd05eeb22462f850a38e30600cedd894d2c6b1eb1a58e9763c
Status: Image is up to date for wordpress:latest
docker.io/library/wordpress:latest

$ docker run --rm wordpress php -m | grep mysql
mysqli
mysqlnd
```

**Comment by TBarregren** [comment]
I ran into the same problem, which turned out to be the volume mapping of the source (`./php`) and the target (/usr/local/etc/php/conf.d). I'm a beginner when it comes to Docker, so I may be wrong, but I thought source and target would be a reflection of each other. But what seems to happen is that my empty source replaces the target, and thus is the mysqli extension never loaded into PHP.

**Comment by tianon** [comment]
When you do a mapping like that, it's called a "bind mount" and it means your local `./php` directory will be mounted inside the container at `/usr/local/etc/php/conf.d` -- so in a way, you're correct, but the "reflection" is one-directional (from the host into the container), which is why you see the behavior that you do.
