### ISSUE TITLE
Can’t select database

### ISSUE THREAD

**Issue by asd99557** [docker-library/wordpress#538]
Hello Team,
I am using docker-compose for creating word press setup.
Using docker-compose.yml file i don't want to share my DB &  WORDPRESS secret with yml file.
I am using .env file save credential in this file will put here yml configuration.
First i am only put MySQL credential, but it's given Can’t select database error.
please help me on this thanks in advance.
version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - wordpress_files:/var/www/html
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: test

   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     env_file:
       - "/root/wordpress/.env"
volumes:
    wordpress_files:
    db_data:

.env configuration 

MYSQL_ROOT_PASSWORD=my_db_root_password
MYSQL_DB=wordpress
MYSQL_USER=wordpress
MYSQL_PASSWORD=test

~                                                                                                                                                     
~

**Comment by wglambert** [comment]
`MYSQL_DB` should be `MYSQL_DATABASE`
https://github.com/docker-library/docs/tree/master/mysql#mysql_database

In the future questions like these should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by asd99557** [comment]
That was syntax issue now it was resolve thanks for your suggestion.
