### ISSUE TITLE
How to install plugin in wordpress setup using docker-compose yml file

### ISSUE THREAD

**Issue by asd99557** [docker-library/wordpress#541]
Want to install word press with w3 total cache plugin using docker-compose yml file.

Any please provide any example may be it possible using bin/bash.sh file file don't have idea about right syntax.

Please help me on this.

**Comment by wglambert** [comment]
The simplest way is to just install it through the `/wp-admin` panel. If you want to do it headless you could use [`wordpress:cli`](https://github.com/docker-library/docs/tree/master/wordpress#wordpresscli) in tandem
https://developer.wordpress.org/cli/commands/plugin/install/

Another option would be to mount a pre-populated `plugins` folder containing the ones you want
https://github.com/docker-library/docs/tree/master/wordpress#include-pre-installed-themes--plugins

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by asd99557** [comment]
Thanks but i want to using docker-compose yml file.
My requirement is when i install word press at this it will automatically install.
How i can write syntax fors plugin install in docker-compose yml.

**Comment by wglambert** [comment]
I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
