### ISSUE TITLE
Pre-installed plugins not updating

### ISSUE THREAD

**Issue by lheazel** [docker-library/wordpress#542]
In [ticket 506](https://github.com/docker-library/wordpress/issues/506), a feature was added to the docker-entrypoint.sh file where during build the application will compare pre-packaged plugins/themes to those existing in a mounted wp-content folder and explicitly not overwrite them if found.

While useful for some use cases, this is antithesis to ours. When we deploy updates of our Wordpress packages with plugins and themes, we include updates to those plugins and themes as part of the bundle. This new functionality is preventing those updates from being applied. Currently we are mounting a custom version of the docker-entrypoint.sh file where this portion of code is commented out. This comes with its own obvious risks.

Proposal: please provide the option for environmental variables in the docker-compose.yml file that allow us to include or exclude overwrite protection for explicit plugins and themes.

**Comment by tianon** [comment]
I guess what's got me confused here is why you have plugins/themes in a persistent volume, but aren't handling updates to them via the built-in WordPress updater?

**Comment by lheazel** [comment]
> I guess what's got me confused here is why you have plugins/themes in a persistent volume, but aren't handling updates to them via the built-in WordPress updater?

Built-in update system requires us to either get the plugin/theme approved by Wordpress (which we hit some snags with) or host the files for updating elsewhere (which we also had some problems with).

Additionally, we operate on a quarterly release schedule which contains all of our updates with one version update in a docker-compose file. These updates span a number of applications including Wordpress.

Additionally, we have a GitHub-AWS pipeline execution system that updates applications in our SIT system when triggered by a corresponding GitHub push. The point of this was to have a push-buttton deployment, which now no longer functions.

**Comment by tianon** [comment]
Ahh, by "pre-installing" you mean you're installing them to `/usr/src/wordpress` in the image?  If you're expecting that to be the canonical source, I'd suggest one of the following:

1. use a tmpfs for `/var/lib/www` so that it's recreated empty every container startup (and thus always freshly initialized)

2. update your image configuration to serve the files directly from `/usr/src/wordpress`, make sure they're not writeable by the `www-data` user (which also gives you some degree of security benefit, assuming you manage the WordPress version updates in a timely manner), and provide a `wp-config.php` at runtime (k8s configmap, etc); alternatively, provide a stock (also read-only) `wp-config.php` in the image itself that uses `getenv` and/or `file_get_contents` for any parameters you need to be able to modify at runtime
