### ISSUE TITLE
Response is empty, cannot serve static files

### ISSUE THREAD

**Issue by myroslambda** [docker-library/wordpress#550]
I am trying to use this image. I'm using this with docker compose and a separate host for the DB.

I'm not moving an existing wordpress, and that is where everything failed.

Essentially, the server responds, but the response body is empty (I get a 200 result code). I have tried to add a static html file to the root (/var/www/html) and I get the same 200 response code, but no contents in the file. I went into the image, installed lynx, connected to localhost and tried to get that static file, and the result is also empty.

I don't find any useful information in the apache logs.

What to do? How can I debug this issue?

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
