### ISSUE TITLE
[Question] How to Setup Redis for Session Management on php-fpm Based Wordpress Image?

### ISSUE THREAD

**Issue by Laraveldeep** [docker-library/wordpress#560]
Hi team,

How do I set up Redis for session management on php-fpm based WordPress image?

I tried to copy my custom ini file at `/usr/local/etc/php/conf.d/php-redis.ini` but I can't see any changes on the mapped `appendonly.aof` file when I log in and out.

php-redis.ini contents
```
session.save_handler = redis
session.save_path = "tcp://redis-session-cache:6379?auth=somepassword"
```

Thanks!

**Comment by wglambert** [comment]
I think you'd use something like this https://wordpress.org/plugins/redis-cache/#installation and then edit the [connection parameters](https://github.com/rhubarbgroup/redis-cache/wiki/Connection-Parameters) to point it at the redis container

But I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
