### ISSUE TITLE
How to add apache module?

### ISSUE THREAD

**Issue by mhrznamn068** [docker-library/wordpress#562]
How to add apache module?

**Comment by wglambert** [comment]
https://github.com/docker-library/wordpress/issues/447#issuecomment-547675267
Since the apache variant is based on the `php:[version]-apache` image, you can use the [Docker Hub docs for php](https://github.com/docker-library/docs/tree/9bdb7f1469737a9c7359853534f8819e0e34b1da/php#changing-documentroot-or-other-apache-configuration).  So, either edit or add conf files somewhere in `/etc/apache2/`, just like a regular Debian install.
