### ISSUE TITLE
WPML and mb_strtolower()

### ISSUE THREAD

**Issue by markorosic** [docker-library/wordpress#58]
Hi guys I'm quite new to Docker and I've been getting this error when trying to activate WPML plugin, any way around this?

Fatal error: Call to undefined function mb_strtolower() in /var/www/html/wp-content/plugins/sitepress-multilingual-cms/inc/sitepress-schema.php on line 464

Not sure if there is something I need to enable in .htaccess or this module is not compiled at all?

**Comment by tianon** [comment]
`mbstring` is not included by default, but something simple like this should get you what you need:
```Dockerfile
FROM wordpress
RUN docker-php-ext-install mbstring
```

Then, use that as your base image instead of `wordpress` -- with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links), it's reasonably easy to have an up-to-date image built `FROM` this one with extra modules enabled.

**Comment by markorosic** [comment]
Thanks for help, that worked.
I was introduced to Docker via project that was well under way, and it was set up using Fig. Although I'm not sure how it handles changes done to containers it obviously auto commits them somehow. I was afraid that adding new thing to DockerFile would re-write my changed container from scratch, but it didn't.

**Comment by Zertz** [comment]
If anyone else stumbles into this problem, I made a very simple image based on wordpress:4.3-apache

https://hub.docker.com/r/zertz/docker-wordpress-extras/
