### ISSUE TITLE
add a VOLUME to wp-content/

### ISSUE THREAD

**Issue by kryton** [docker-library/wordpress#6]
not sure what your feelings are about this, but it would be handy to have this exposed.

1. wp-content/uploads is where images and other user-uploaded content gets put, so you need a way to back it up

2. it allows people to easily add/update themes/plugins

**Comment by yosifkit** [comment]
Closing as we currently have `VOLUME /var/www/html` which covers this and if there is desire to remove the volume, then a new discussion can be opened for that.

**Comment by agherzan** [comment]
I'm not sure why was this dropped and why don't we consider at least documenting this mount. The whole idea of a docker container is to be able to update a component at the image level. If I persist that component in the docker container, why should I use docker in the first place? If I don't mount /var/www/html and update the container, I will lose all my data that does not reside in the database (ex plugins, themes, uploads etc).

So the problem @kryton raised is crucial and actually I have no idea how user would use this image otherwise.

**Comment by Gymnae** [comment]
I just ran into this with an upgrade of Wordpress. I can either demount my volume container to upgrade to the new version, but doing so lose plugins and themes, or link an ftp container to my wordpress container.

The problematic file wp-content and the folder wp-content need to be user mounted and persistently stored, the rest should be "docker like" and not persistently stored. 

How could this be achieved?

**Comment by surtic86** [comment]
Still a Problem or is there any other easy fix?

**Comment by drzraf** [comment]
#282
