### ISSUE TITLE
Image for 5.7.1 pushed/updated multiple times

### ISSUE THREAD

**Issue by jokay** [docker-library/wordpress#606]
Is there a specific reason, why the images on [hub.docker.com](https://hub.docker.com/_/wordpress?tab=tags&page=1&ordering=last_updated&name=5.7.1) for **5.7.1** have been pushed/updated multiple times?
Already 3 times today :wink:

Seems to be related to the [php](https://hub.docker.com/_/php) image?

**Comment by jokay** [comment]
4 times ...

... seems to be a feature, I close this issue.

**Comment by tianon** [comment]
Yep, that's intentional -- looking through https://github.com/docker-library/repo-info/commits/master/repos/wordpress/remote/5.7.1.md, I can see that these rebuilds were triggered by the update to PHP 7.4.18 (https://github.com/docker-library/official-images/pull/10088), which probably took some time to update across all the different architectures supported, which is why you see the manifest list updated multiple times for the "same" change (not all the architectures are quite as fast as others).
