### ISSUE TITLE
updates not installed to runtime directory

### ISSUE THREAD

**Issue by keis** [docker-library/wordpress#64]
I'm trying to build a container derived from the wordpress image with my themes and plugins already in place. This works fine when starting from a fresh volume but after it's installed no updates I push to the /usr/src/wordpress takes effect.

looking at the entrypoint script this seems to be intentional but it would be nice to have a way of bypassing the already installed check and always rsync (or tar).

**Comment by tianon** [comment]
Wow, sorry for the *uber*-long delay in response here. :disappointed:

I'm sure you've probably already found a solution or workaround by now, but for posterity, I think your best bet is going to be to not persist the `/var/www/html` volume between container starts, and only persist `wp-content/uploads` or whatever is actually important.  Another option would be to adjust the configuration/script to use a different directory so that it's not a volume at all, and thus no chance of even `docker-compose` saving it for you.

If the use case you're after is a development/debugging container that you cycle periodically to test your plugins/themes, a pattern that's been pretty successful for us is to bind-mount the local copy into the running container directly (`-v "$PWD":/var/www/html/wp-content/themes/my-theme`, etc).
