### ISSUE TITLE
Add php extension intl by default?

### ISSUE THREAD

**Issue by mathsen** [docker-library/wordpress#685]
Hello,

since the update to Wordpress 5.9, the "site health checker" recommends to install the intl php extension.
This has further been explained in [this blog post](https://make.wordpress.org/hosting/2021/05/20/why-hosters-should-install-the-php-intl-extension/).
Maybe this extension should be added to the default docker images?
I could  make a pull request, if there are no objections.

Greetings

Mathse

**Comment by tianon** [comment]
Ah, good catch -- I think a link to https://core.trac.wordpress.org/ticket/52654 is probably useful too (the issue that added it to Site Health).  I agree that we should add it given Site Health requests it (we should do what we can to make sure Site Health is as green out-of-the-box as we can make it, since it represents "official upstream recommendations" which is our entire goal :sweat_smile:).

**Comment by mathsen** [comment]
Thanks everybody for the quick fix!
