### ISSUE TITLE
How to access debug.log and .htaccess?

### ISSUE THREAD

**Issue by marcwiest** [docker-library/wordpress#700]
Hi there,  I'm just trying out docker for local development and it's working well. The only thing I'm having trouble wrapping my head around is, how can I get a hold of the `debug.log` and `.htaccess` files? I'd prefer to have a copy on the host that is in sync with what's on the named volume. I know I can save a copy via the Volumes through Docker desktop app, but that's a cumbersome process.

Any recommendations on how to set up a `docker-compose.yml` that would help with that?
Thanks

**Comment by wglambert** [comment]
Those files are at `/var/www/html/wp-content/debug.log` and `/var/www/html/.htaccess`

In your compose file you can include a volume section like https://github.com/docker-library/wordpress/issues/559#issue-783170378
https://github.com/docker-library/wordpress/issues/595 could also be relevant

In the future questions like these should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
