### ISSUE TITLE
Changing domain name

### ISSUE THREAD

**Issue by vawaver** [docker-library/wordpress#703]
Good morning,
I would like to ask you for a tutorial on how to change domain name.
I bought a new domain and like to change my web from the old domain to a new one.
Thank you.

**Comment by wglambert** [comment]
There's already a few out there. Searching for "docker wordpress change url" gets me https://techsch.com/tutorials/change-domain-wordpress-docker-phpmyadmin as the first link and it's recent within a couple years

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
