### ISSUE TITLE
Snyk reports four 9.8 grade vulnerabilites in wordpress:php7.4-fpm

### ISSUE THREAD

**Issue by isvaljek** [docker-library/wordpress#737]
Snyk reports four 9.8 / 10 grade vulnerabilities in wordpress:php7.4-fpm, three of them are ImageMagick related. Will there be an updated version?
I have to stick to php 7.4 for now, because of an Oracle Client dependency.

**Comment by wglambert** [comment]
It'll get updated on its usual monthly cadence. Because our build system makes such heavy use of the Docker build cache it requires base image updates to propagate changes for the dependent images

Background: 
>Tags in the [official-images] library file[s] are only built through an update to that library file or as a result of its base image being updated (ie, an image `FROM debian:buster` would be rebuilt when `debian:buster` is built). 
>
>\-https://github.com/docker-library/official-images/tree/2f086314307c04e1de77f0a515f20671e60d40bb#library-definition-files

Official Images FAQ:

> Though not every CVE is removed from the images, we take CVEs seriously and try to ensure that images contain the most up-to-date packages available within a reasonable time frame
>
> \- https://github.com/docker-library/faq/tree/6138d05aabf61563606d86f98d0ccbd99f162b33#why-does-my-security-scanner-show-that-an-image-has-cves

Since our build system makes heavy use of Docker build cache, just rebuilding the all of the Dockerfiles won't cause any change. So we rely on periodic base image updates.

> We strive to publish updated images at least monthly for Debian and Ubuntu. We also rebuild earlier if there is a critical security need. Many Official Images are maintained by the community or their respective upstream projects, like Alpine and Oracle Linux, and are subject to their own maintenance schedule.
>
> \- from the same FAQ link

**Comment by tianon** [comment]
If any of these are fixed in Debian, they'll be fixed for supported tags via https://github.com/docker-library/official-images/pull/13132
