### ISSUE TITLE
set max upload size via env variables

### ISSUE THREAD

**Issue by debritde** [docker-library/wordpress#741]
Hello,
after years of using it, i ask my self again and again why i have to manually access the container and edit the .htaccess to have a reasonable upload size limit.
PLEASE add it as an env variable.
This is very simple and necessary to avoid touching the container manually after installing

**Comment by tianon** [comment]
I would suggest creating a short `Dockerfile` which is `FROM wordpress:xxx` and applies any changes you might need repeatably in an image (instead of doing them at runtime) -- in this case, doing so in `php.ini` would be appropriate.

For further help, I would suggest a dedicated support forum, such as [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
