### ISSUE TITLE
Alpine image not updated since 1 december

### ISSUE THREAD

**Issue by ferronsw** [docker-library/wordpress#789]
Hi,

According to the docker hub the alpine build hasn't been run since the 1 of December:
https://hub.docker.com/_/wordpress/tags?page=1&name=6-fpm-alpine

The last alpine docker build in Jenkins was completed on December 20th.
On what schedule should images be build?

**Comment by wglambert** [comment]
6.0 isn't actively supported since 6.1 is out
https://endoflife.date/wordpress

**Comment by yosifkit** [comment]
Background: 
>Tags in the [official-images] library file[s] are only built through an update to that library file or as a result of its base image being updated (ie, an image `FROM debian:buster` would be rebuilt when `debian:buster` is built). 
>
>\-https://github.com/docker-library/official-images/tree/2f086314307c04e1de77f0a515f20671e60d40bb#library-definition-files

Since our build system makes heavy use of Docker build cache, just rebuilding the all of the Dockerfiles won't cause any change. So we rely on periodic base image updates.

> We strive to publish updated images at least monthly for Debian. We also rebuild earlier if there is a critical security need. Many Official Images are maintained by the community or their respective upstream projects, like Ubuntu, Alpine, and Oracle Linux, and are subject to their own maintenance schedule.
>
> \- from the same FAQ link

So, all the actively supported tags of WordPress have been built since their respective base images have been built or more recently for any Dockerfile changes, like https://github.com/docker-library/official-images/pull/13624 that included a tag change of `6-fpm-alpine` to no longer be equal to `6.1.1-php7.4-fpm-alpine` and instead be equivalent to `6.1.1-php8.0-fpm-alpine`.
