### ISSUE TITLE
why mod_php in 2024?

### ISSUE THREAD

**Issue by mihaiav** [docker-library/wordpress#889]
Why the apache repository is using mod_php instead fastcgi / php-fpm in 2024? Even apache recommends using fastcgi.

**Comment by tianon** [comment]
Because we cannot create a ["single process per container"](https://github.com/docker-library/official-images#init) installation that uses FastCGI / PHP-FPM out-of-the-box (due to Apache not being able/willing to manage FastCGI processes on our behalf), so we have the default Apache variant which will run successfully for most users right away and the PHP-FPM variant which requires a _lot_ more fiddly environment/configuration setup.
