### ISSUE TITLE
Changes Not Saving

### ISSUE THREAD

**Issue by dillardmurphy** [docker-library/wordpress#99]
Hello,

I have created a MYSQL database image, a Wordpress image, and a working directory in Docker. I was able to copy a new theme file and a new slider plugin to their correct folders. In the browser(localhost), everything works and I am able to view the site and save changes.

I commit and push the changes from one machine and pull them from another machine. I am able to view the site in the browser but the original theme is displaying. When I check the file system, the new theme and the plugin are not there. Any thoughts? 

Thanks in Advance!

**Comment by md5** [comment]
Using `docker commit` with this image will not work since `/var/www/html` is a volume. If you want to move the container to another machine, you'll need to copy and reuse the contents of the original volume.

**Comment by staff0rd** [comment]
Came here for this, which is (now I understand) obviously a docker issue rather than a wordpress one.  I ended up using `docker cp` to copy `/var/www/html/ from my existing container somewhere locally, and then after executing `docker run` copying the local files back into the new container.

This however makes me think that the `commit` is superfluous.

**Comment by yosifkit** [comment]
Instead of the second `docker cp` to put things back in the container, you could just use a bind mounted volume `-v /home/user/html:/var/www/html` on the docker run :smile:. The files from a volume are never added to a `commit` but are for things that you want to persist outside of the container lifecycle.

Another alternative is to just use the files in a new container:
```console
$ docker rename blog old-blog
$ docker stop old-blog
$ docker run --name blog --link some-mysql:mysql -d --volumes-from old-blog wordpress
$ docker rm old-blog
```
